FROM python:3.8 as django-api

WORKDIR /opt/app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV UWSGI_PROCESSES 1
ENV UWSGI_THREADS 16
ENV UWSGI_HARAKIRI 240
ENV DJANGO_SETTINGS_MODULE 'config.settings'
ENV PIP_ROOT_USER_ACTION=ignore


RUN groupadd -r django && useradd -d /opt/app -r -g django django \
    && chown django:django -R /opt/app/

COPY requirements.txt requirements.txt
COPY uwsgi/uwsgi.ini uwsgi.ini

RUN python -m pip install --upgrade  pip && pip install -r requirements.txt

COPY . .

RUN chmod +x docker-entrypoint.sh

RUN ./manage.py collectstatic --noinput
RUN ./manage.py makemigrations movies

EXPOSE 8000

USER django
ENTRYPOINT ["/opt/app/docker-entrypoint.sh"]


FROM nginx:1.25.1-alpine as proxy

COPY --from=django-api /opt/app/static /data/static